import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const CATEGORIES = [
  {
    name: "Anime",
    slug: "anime",
    description: "High-resolution Japanese anime scenes, stylized character portraits, and vibrant fantasy animation backdrops in crisp 4K.",
    coverImage: "https://images.unsplash.com/photo-1578632767115-351597cf2477?auto=format&fit=crop&w=1200&q=80",
    order: 1,
  },
  {
    name: "Gaming",
    slug: "gaming",
    description: "Iconic gaming environments, futuristic battle arenas, glowing gamer battle-stations, and concept art tailored for gaming PCs.",
    coverImage: "https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=1200&q=80",
    order: 2,
  },
  {
    name: "Cars",
    slug: "cars",
    description: "Exotic hypercars, vintage classics, sleek nocturnal street racers, and automotive engineering masterpieces.",
    coverImage: "https://images.unsplash.com/photo-1617814076367-b759c7d7e738?auto=format&fit=crop&w=1200&q=80",
    order: 3,
  },
  {
    name: "Nature",
    slug: "nature",
    description: "Breathtaking mountain peaks, deep mist-shrouded forests, pristine waterfalls, and panoramic wilderness.",
    coverImage: "https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?auto=format&fit=crop&w=1200&q=80",
    order: 4,
  },
  {
    name: "Space",
    slug: "space",
    description: "Stellar nebulae, distant spiral galaxies, lunar horizons, and deep cosmic mysteries rendered in 4K brilliance.",
    coverImage: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=1200&q=80",
    order: 5,
  },
  {
    name: "Minimal",
    slug: "minimal",
    description: "Clean geometric shapes, tranquil negative space, balanced shadows, and distraction-free desktop aesthetics.",
    coverImage: "https://images.unsplash.com/photo-1494438639946-1ebd1d20bf85?auto=format&fit=crop&w=1200&q=80",
    order: 6,
  },
  {
    name: "Abstract",
    slug: "abstract",
    description: "Surreal 3D renders, liquid gradients, chromatic waves, and tactile dimensional art.",
    coverImage: "https://images.unsplash.com/photo-1541701494587-cb58502866ab?auto=format&fit=crop&w=1200&q=80",
    order: 7,
  },
  {
    name: "Cyberpunk",
    slug: "cyberpunk",
    description: "Rain-slicked neon alleys, holographic skylines, cybernetic megacities, and high-tech dystopian vistas.",
    coverImage: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=1200&q=80",
    order: 8,
  },
  {
    name: "Technology",
    slug: "technology",
    description: "Microcircuits, server rooms, illuminated silicone wafers, quantum chips, and futuristic hardware.",
    coverImage: "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1200&q=80",
    order: 9,
  },
  {
    name: "Architecture",
    slug: "architecture",
    description: "Dramatic cantilevered facades, brutalist monuments, soaring glass skyscrapers, and architectural symmetry.",
    coverImage: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200&q=80",
    order: 10,
  },
  {
    name: "Movies",
    slug: "movies",
    description: "Cinematic widescreen frames, dramatic atmospheric compositions, and movie-grade visual spectacles.",
    coverImage: "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=1200&q=80",
    order: 11,
  },
  {
    name: "Superheroes",
    slug: "superheroes",
    description: "Dynamic comic-inspired hero silhouettes, glowing emblems, and epic metropolitan guardian art.",
    coverImage: "https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=1200&q=80",
    order: 12,
  },
  {
    name: "Animals",
    slug: "animals",
    description: "Intimate wildlife portraits, predatory gaze in high-definition, and wildlife in their natural habitat.",
    coverImage: "https://images.unsplash.com/photo-1561731216-c3a4d99437d5?auto=format&fit=crop&w=1200&q=80",
    order: 13,
  },
  {
    name: "Dark",
    slug: "dark",
    description: "Deep true black OLED wallpapers, subtle low-key lighting, moody shadows, and minimal battery-saving aesthetics.",
    coverImage: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=1200&q=80",
    order: 14,
  },
  {
    name: "Aesthetic",
    slug: "aesthetic",
    description: "Pastel lo-fi gradients, retro synthwave sunsets, nostalgic film grain, and gentle ambient vibes.",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80",
    order: 15,
  },
  {
    name: "City",
    slug: "city",
    description: "Dusk-lit metropolis skylines, Tokyo nocturnal crossings, New York aerials, and European cobblestone charms.",
    coverImage: "https://images.unsplash.com/photo-1514565131-fce0801e5785?auto=format&fit=crop&w=1200&q=80",
    order: 16,
  },
  {
    name: "Fantasy",
    slug: "fantasy",
    description: "Mythical floating citadels, arcane rune forests, dragon spires, and epic otherworldly realms.",
    coverImage: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=1200&q=80",
    order: 17,
  },
  {
    name: "Sports",
    slug: "sports",
    description: "Extreme sports adrenaline, high-speed downhill skiing, stadium night lights, and athletic action moments.",
    coverImage: "https://images.unsplash.com/photo-1461896836934-ffe607ba8211?auto=format&fit=crop&w=1200&q=80",
    order: 18,
  },
];

const COLLECTIONS = [
  {
    name: "Best 4K Gaming Wallpapers",
    slug: "best-4k-gaming-wallpapers",
    description: "Curated high-intensity gaming visuals, cyber battlegrounds, and pixel-perfect PC desktop backdrops.",
    coverImage: "https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=1200&q=80",
    featured: true,
  },
  {
    name: "Best Dark Wallpapers",
    slug: "best-dark-wallpapers",
    description: "Stealthy, OLED-optimized desktop wallpapers with pitch blacks, moody contrasts, and zero eye-strain.",
    coverImage: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=1200&q=80",
    featured: true,
  },
  {
    name: "Best Anime Wallpapers",
    slug: "best-anime-wallpapers",
    description: "Stunning aesthetic anime horizons, celestial skies, and iconic stylized illustrations.",
    coverImage: "https://images.unsplash.com/photo-1578632767115-351597cf2477?auto=format&fit=crop&w=1200&q=80",
    featured: true,
  },
  {
    name: "Best Car Wallpapers",
    slug: "best-car-wallpapers",
    description: "High-octane sports cars, neon street drifting, and clean automotive studio photography in 4K.",
    coverImage: "https://images.unsplash.com/photo-1617814076367-b759c7d7e738?auto=format&fit=crop&w=1200&q=80",
    featured: true,
  },
  {
    name: "Best Minimal Wallpapers",
    slug: "best-minimal-wallpapers",
    description: "Quiet elegance for focused workspaces. Minimal compositions, architectural lines, and soothing tones.",
    coverImage: "https://images.unsplash.com/photo-1494438639946-1ebd1d20bf85?auto=format&fit=crop&w=1200&q=80",
    featured: true,
  },
  {
    name: "Best Wallpapers for Dual Monitors & Ultrawide",
    slug: "dual-monitors-and-ultrawide",
    description: "Expansive panoramic artwork meticulously framed for 21:9 ultrawide and 32:9 dual monitor setups.",
    coverImage: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80",
    featured: true,
  },
  {
    name: "Cyberpunk & Neon Cityscapes",
    slug: "cyberpunk-neon-cityscapes",
    description: "Immersive dystopian skylines drenched in electric magenta, cyan glows, and rainy reflections.",
    coverImage: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=1200&q=80",
    featured: false,
  },
  {
    name: "Deep Space & Cosmic Horizons",
    slug: "deep-space-cosmic-horizons",
    description: "Witness distant stellar nurseries, black hole lensing, orbital views, and cosmic wonder.",
    coverImage: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=1200&q=80",
    featured: false,
  },
  {
    name: "Cinematic & Superhero Universe",
    slug: "cinematic-superhero-universe",
    description: "Moody superhero silhouettes, dramatic lightning strikes, and comic blockbuster aesthetics.",
    coverImage: "https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=1200&q=80",
    featured: false,
  },
  {
    name: "Aesthetic Nature & Wilderness",
    slug: "aesthetic-nature-wilderness",
    description: "Alpine glaciers, Norwegian fjords, autumn maple forests, and calming scenic landscapes.",
    coverImage: "https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?auto=format&fit=crop&w=1200&q=80",
    featured: false,
  },
];

interface RawWallpaper {
  title: string;
  slug: string;
  categorySlug: string;
  description: string;
  width: number;
  height: number;
  orientation: "landscape" | "portrait" | "ultrawide";
  rawUrl: string;
  fileType: string;
  fileSize: string;
  views: number;
  downloads: number;
  featured: boolean;
  trending: boolean;
  creatorName: string;
  creatorUrl: string;
  tags: string[];
  collectionSlugs?: string[];
}

const RAW_WALLPAPERS: RawWallpaper[] = [
  // CYBERPUNK
  {
    title: "Neon Cyberpunk City Night",
    slug: "neon-cyberpunk-city-night",
    categorySlug: "cyberpunk",
    description: "A rain-drenched futuristic megacity glowing under towering holographic billboards and electric neon signs in 4K resolution.",
    width: 3840,
    height: 2160,
    orientation: "landscape",
    rawUrl: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5",
    fileType: "WEBP",
    fileSize: "6.8 MB",
    views: 34200,
    downloads: 14890,
    featured: true,
    trending: true,
    creatorName: "Ales Krivec",
    creatorUrl: "https://unsplash.com/@aleskrivec",
    tags: ["cyberpunk", "neon", "city", "future", "rain", "night", "dark"],
    collectionSlugs: ["cyberpunk-neon-cityscapes", "best-dark-wallpapers"],
  },
  {
    title: "Cybernetic Alleyway Tokyo",
    slug: "cybernetic-alleyway-tokyo",
    categorySlug: "cyberpunk",
    description: "Atmospheric narrow Tokyo alleyway drenched in magenta neon glow, steam, and cinematic reflections.",
    width: 3840,
    height: 2160,
    orientation: "landscape",
    rawUrl: "https://images.unsplash.com/photo-1503899036084-c55cdd92da26",
    fileType: "WEBP",
    fileSize: "5.9 MB",
    views: 28400,
    downloads: 11200,
    featured: true,
    trending: true,
    creatorName: "Liam Wong",
    creatorUrl: "https://unsplash.com",
    tags: ["tokyo", "cyberpunk", "japan", "neon", "alley", "aesthetic"],
    collectionSlugs: ["cyberpunk-neon-cityscapes"],
  },
  {
    title: "Neo Metropolis Highrise",
    slug: "neo-metropolis-highrise",
    categorySlug: "cyberpunk",
    description: "Towering monolithic skyscrapers shrouded in luminescent smog and high-tech aerial traffic routes.",
    width: 3840,
    height: 2160,
    orientation: "landscape",
    rawUrl: "https://images.unsplash.com/photo-1514565131-fce0801e5785",
    fileType: "WEBP",
    fileSize: "6.4 MB",
    views: 19800,
    downloads: 8750,
    featured: false,
    trending: true,
    creatorName: "Sasha Freemind",
    creatorUrl: "https://unsplash.com",
    tags: ["metropolis", "cyberpunk", "skyline", "buildings", "dark"],
    collectionSlugs: ["cyberpunk-neon-cityscapes"],
  },

  // GAMING
  {
    title: "Futuristic Mech Arena",
    slug: "futuristic-mech-arena",
    categorySlug: "gaming",
    description: "An intense futuristic esports arena with glowing geometric light bars and cybernetic battle platforms.",
    width: 3840,
    height: 2160,
    orientation: "landscape",
    rawUrl: "https://images.unsplash.com/photo-1542751371-adc38448a05e",
    fileType: "WEBP",
    fileSize: "7.1 MB",
    views: 45200,
    downloads: 21900,
    featured: true,
    trending: true,
    creatorName: "Florian Olivo",
    creatorUrl: "https://unsplash.com",
    tags: ["gaming", "esports", "arena", "neon", "rgb", "pc"],
    collectionSlugs: ["best-4k-gaming-wallpapers"],
  },
  {
    title: "RGB Battle Station Glow",
    slug: "rgb-battle-station-glow",
    categorySlug: "gaming",
    description: "Ultra clean minimalist mechanical keyboard and ambient violet neon glow from a master PC gaming setup.",
    width: 3840,
    height: 2160,
    orientation: "landscape",
    rawUrl: "https://images.unsplash.com/photo-1550745165-9bc0b252726f",
    fileType: "WEBP",
    fileSize: "5.4 MB",
    views: 31200,
    downloads: 13500,
    featured: true,
    trending: false,
    creatorName: "Lorenzo Herrera",
    creatorUrl: "https://unsplash.com",
    tags: ["gaming", "setup", "rgb", "desk", "tech", "hardware"],
    collectionSlugs: ["best-4k-gaming-wallpapers"],
  },
  {
    title: "Retro Arcade Vaporwave Grid",
    slug: "retro-arcade-vaporwave-grid",
    categorySlug: "gaming",
    description: "Glowing neon wireframe grid receding into an infinite digital horizon with synthwave retro aesthetic.",
    width: 3840,
    height: 2160,
    orientation: "landscape",
    rawUrl: "https://images.unsplash.com/photo-1579546929518-9e396f3cc809",
    fileType: "WEBP",
    fileSize: "4.8 MB",
    views: 22100,
    downloads: 9400,
    featured: false,
    trending: true,
    creatorName: "Evie S.",
    creatorUrl: "https://unsplash.com",
    tags: ["gaming", "synthwave", "vaporwave", "retro", "grid", "80s"],
    collectionSlugs: ["best-4k-gaming-wallpapers"],
  },

  // ANIME
  {
    title: "Shinto Shrine Twilight Blossom",
    slug: "shinto-shrine-twilight-blossom",
    categorySlug: "anime",
    description: "Traditional crimson torii gate illuminated by warm lanterns under a cascading pink cherry blossom canopy and starry sky.",
    width: 3840,
    height: 2160,
    orientation: "landscape",
    rawUrl: "https://images.unsplash.com/photo-1578632767115-351597cf2477",
    fileType: "WEBP",
    fileSize: "6.2 MB",
    views: 52100,
    downloads: 24800,
    featured: true,
    trending: true,
    creatorName: "Sora Studios",
    creatorUrl: "https://unsplash.com",
    tags: ["anime", "japan", "torii", "sakura", "twilight", "scenery"],
    collectionSlugs: ["best-anime-wallpapers"],
  },
  {
    title: "Celestial Anime Horizon",
    slug: "celestial-anime-horizon",
    categorySlug: "anime",
    description: "Dreamy anime fantasy landscape with twin moons, glowing bioluminescent clouds, and crystalline reflections.",
    width: 3840,
    height: 2160,
    orientation: "landscape",
    rawUrl: "https://images.unsplash.com/photo-1534447677768-be436bb09401",
    fileType: "WEBP",
    fileSize: "6.7 MB",
    views: 41900,
    downloads: 18700,
    featured: true,
    trending: true,
    creatorName: "Kimi No Sekai",
    creatorUrl: "https://unsplash.com",
    tags: ["anime", "clouds", "sky", "fantasy", "stars", "moon"],
    collectionSlugs: ["best-anime-wallpapers"],
  },
  {
    title: "Rainy Anime Street Lamp",
    slug: "rainy-anime-street-lamp",
    categorySlug: "anime",
    description: "Cozy rainy evening in an anime suburb with amber streetlamps reflecting onto glistening asphalt puddle mirrors.",
    width: 3840,
    height: 2160,
    orientation: "landscape",
    rawUrl: "https://images.unsplash.com/photo-1519501025264-65ba15a82390",
    fileType: "WEBP",
    fileSize: "5.1 MB",
    views: 29800,
    downloads: 12400,
    featured: false,
    trending: false,
    creatorName: "Makoto Vibe",
    creatorUrl: "https://unsplash.com",
    tags: ["anime", "rain", "cozy", "aesthetic", "street", "night"],
    collectionSlugs: ["best-anime-wallpapers"],
  },

  // CARS
  {
    title: "Matte Black Supercar Dusk",
    slug: "matte-black-supercar-dusk",
    categorySlug: "cars",
    description: "Aggressive aerodynamic hypercar in satin matte black parked beneath twilight canyon cliffs.",
    width: 3840,
    height: 2160,
    orientation: "landscape",
    rawUrl: "https://images.unsplash.com/photo-1617814076367-b759c7d7e738",
    fileType: "WEBP",
    fileSize: "7.4 MB",
    views: 48900,
    downloads: 22100,
    featured: true,
    trending: true,
    creatorName: "Campbell",
    creatorUrl: "https://unsplash.com",
    tags: ["supercar", "cars", "black", "hypercar", "speed", "dark"],
    collectionSlugs: ["best-car-wallpapers", "best-dark-wallpapers"],
  },
  {
    title: "Porsche GT3 RS Track Apex",
    slug: "porsche-gt3-rs-track-apex",
    categorySlug: "cars",
    description: "Crisp 4K tracking shot of a high-performance track weapon hitting the apex with carbon fiber spoiler aerodynamics.",
    width: 3840,
    height: 2160,
    orientation: "landscape",
    rawUrl: "https://images.unsplash.com/photo-1503376780353-7e6692767b70",
    fileType: "WEBP",
    fileSize: "6.9 MB",
    views: 39400,
    downloads: 16800,
    featured: true,
    trending: true,
    creatorName: "Olga Subach",
    creatorUrl: "https://unsplash.com",
    tags: ["porsche", "racing", "cars", "speed", "track"],
    collectionSlugs: ["best-car-wallpapers"],
  },
  {
    title: "Vintage Mustang Sunset Cruise",
    slug: "vintage-mustang-sunset-cruise",
    categorySlug: "cars",
    description: "Classic American muscle car cruising down coastal highway bathed in warm golden hour sunlight.",
    width: 3840,
    height: 2160,
    orientation: "landscape",
    rawUrl: "https://images.unsplash.com/photo-1584345604476-8ec5e12e42dd",
    fileType: "WEBP",
    fileSize: "5.8 MB",
    views: 24700,
    downloads: 9800,
    featured: false,
    trending: false,
    creatorName: "Joey Banks",
    creatorUrl: "https://unsplash.com",
    tags: ["classic", "mustang", "vintage", "cars", "sunset", "goldenhour"],
    collectionSlugs: ["best-car-wallpapers"],
  },

  // NATURE
  {
    title: "Misty Alpine Peak Sunrise",
    slug: "misty-alpine-peak-sunrise",
    categorySlug: "nature",
    description: "Towering snow-capped mountain ridge piercing through morning cloud inversions illuminated in warm amber rays.",
    width: 3840,
    height: 2160,
    orientation: "landscape",
    rawUrl: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b",
    fileType: "WEBP",
    fileSize: "8.1 MB",
    views: 61200,
    downloads: 29800,
    featured: true,
    trending: true,
    creatorName: "Kalon Cochrane",
    creatorUrl: "https://unsplash.com",
    tags: ["mountains", "nature", "alps", "sunrise", "clouds", "4k"],
    collectionSlugs: ["aesthetic-nature-wilderness"],
  },
  {
    title: "Emerald Forest Canopy Mist",
    slug: "emerald-forest-canopy-mist",
    categorySlug: "nature",
    description: "Lush ancient pine forest draped in ethereal morning fog, creating a soothing natural haven for desktop screens.",
    width: 3840,
    height: 2160,
    orientation: "landscape",
    rawUrl: "https://images.unsplash.com/photo-1448375240586-882707db888b",
    fileType: "WEBP",
    fileSize: "7.6 MB",
    views: 43200,
    downloads: 19400,
    featured: true,
    trending: false,
    creatorName: "Sebastian Unrau",
    creatorUrl: "https://unsplash.com",
    tags: ["forest", "trees", "mist", "green", "nature", "calm"],
    collectionSlugs: ["aesthetic-nature-wilderness"],
  },
  {
    title: "Arctic Glacier Turquoise Lagoon",
    slug: "arctic-glacier-turquoise-lagoon",
    categorySlug: "nature",
    description: "Deep azure glacial meltwaters reflecting colossal ice formations in pristine northern wilderness.",
    width: 3840,
    height: 2160,
    orientation: "landscape",
    rawUrl: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e",
    fileType: "WEBP",
    fileSize: "6.5 MB",
    views: 31000,
    downloads: 14200,
    featured: false,
    trending: true,
    creatorName: "Sean Oulashin",
    creatorUrl: "https://unsplash.com",
    tags: ["glacier", "water", "ice", "nature", "blue", "serene"],
    collectionSlugs: ["aesthetic-nature-wilderness"],
  },

  // SPACE
  {
    title: "Deep Cosmos Spiral Nebula",
    slug: "deep-cosmos-spiral-nebula",
    categorySlug: "space",
    description: "Vivid ultraviolet and cosmic dust trails forming an interstellar stellar nursery across a dense starfield.",
    width: 3840,
    height: 2160,
    orientation: "landscape",
    rawUrl: "https://images.unsplash.com/photo-1451187580459-43490279c0fa",
    fileType: "WEBP",
    fileSize: "8.9 MB",
    views: 58900,
    downloads: 27500,
    featured: true,
    trending: true,
    creatorName: "NASA / Hubble",
    creatorUrl: "https://unsplash.com",
    tags: ["space", "nebula", "galaxy", "stars", "cosmos", "astronomy"],
    collectionSlugs: ["deep-space-cosmic-horizons"],
  },
  {
    title: "Earth Horizon From Orbit",
    slug: "earth-horizon-from-orbit",
    categorySlug: "space",
    description: "The delicate azure curvature of planet Earth glowing against the pitch-black void of deep space.",
    width: 3840,
    height: 2160,
    orientation: "landscape",
    rawUrl: "https://images.unsplash.com/photo-1614728894747-a83421e2b9c9",
    fileType: "WEBP",
    fileSize: "6.8 MB",
    views: 47100,
    downloads: 21300,
    featured: true,
    trending: true,
    creatorName: "NASA Archive",
    creatorUrl: "https://unsplash.com",
    tags: ["earth", "space", "orbit", "planet", "blue", "horizon"],
    collectionSlugs: ["deep-space-cosmic-horizons"],
  },
  {
    title: "Milky Way Arch Desert Night",
    slug: "milky-way-arch-desert-night",
    categorySlug: "space",
    description: "The galactic core of the Milky Way arching majestically over weathered red rock monoliths.",
    width: 3840,
    height: 2160,
    orientation: "landscape",
    rawUrl: "https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86",
    fileType: "WEBP",
    fileSize: "7.2 MB",
    views: 35600,
    downloads: 15400,
    featured: false,
    trending: false,
    creatorName: "Jeremy Thomas",
    creatorUrl: "https://unsplash.com",
    tags: ["milkyway", "stars", "desert", "astrophotography", "night"],
    collectionSlugs: ["deep-space-cosmic-horizons"],
  },

  // MINIMAL
  {
    title: "Architectural Concrete Shadows",
    slug: "architectural-concrete-shadows",
    categorySlug: "minimal",
    description: "Subtle brutalist geometric concrete angles casting sharp diagonal shadows in stark minimalist harmony.",
    width: 3840,
    height: 2160,
    orientation: "landscape",
    rawUrl: "https://images.unsplash.com/photo-1494438639946-1ebd1d20bf85",
    fileType: "WEBP",
    fileSize: "4.1 MB",
    views: 38700,
    downloads: 17200,
    featured: true,
    trending: true,
    creatorName: "Simone Hutsch",
    creatorUrl: "https://unsplash.com",
    tags: ["minimal", "architecture", "concrete", "shadows", "clean", "simple"],
    collectionSlugs: ["best-minimal-wallpapers"],
  },
  {
    title: "Dark Minimal Monolith Horizon",
    slug: "dark-minimal-monolith-horizon",
    categorySlug: "minimal",
    description: "Solitary obsidian pillar standing silent against a misty gradient grayscale sea horizon.",
    width: 3840,
    height: 2160,
    orientation: "landscape",
    rawUrl: "https://images.unsplash.com/photo-1507499739999-097706ad8914",
    fileType: "WEBP",
    fileSize: "3.8 MB",
    views: 32400,
    downloads: 14600,
    featured: true,
    trending: false,
    creatorName: "Dan Freeman",
    creatorUrl: "https://unsplash.com",
    tags: ["minimal", "monolith", "dark", "zen", "horizon", "clean"],
    collectionSlugs: ["best-minimal-wallpapers", "best-dark-wallpapers"],
  },
  {
    title: "Warm Desert Sand Dune Ripple",
    slug: "warm-desert-sand-dune-ripple",
    categorySlug: "minimal",
    description: "Gentle natural wave ripples formed by wind across ochre desert sand in peaceful isolation.",
    width: 3840,
    height: 2160,
    orientation: "landscape",
    rawUrl: "https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9",
    fileType: "WEBP",
    fileSize: "4.5 MB",
    views: 26500,
    downloads: 11100,
    featured: false,
    trending: false,
    creatorName: "Luca Bravo",
    creatorUrl: "https://unsplash.com",
    tags: ["dune", "desert", "minimal", "texture", "warm", "sand"],
    collectionSlugs: ["best-minimal-wallpapers"],
  },

  // ABSTRACT
  {
    title: "Prismatic Fluid Wave 4K",
    slug: "prismatic-fluid-wave-4k",
    categorySlug: "abstract",
    description: "Mesmerizing iridescent liquid silk ribbon folding gracefully in deep three-dimensional space.",
    width: 3840,
    height: 2160,
    orientation: "landscape",
    rawUrl: "https://images.unsplash.com/photo-1541701494587-cb58502866ab",
    fileType: "WEBP",
    fileSize: "6.3 MB",
    views: 44100,
    downloads: 19800,
    featured: true,
    trending: true,
    creatorName: "Steve Johnson",
    creatorUrl: "https://unsplash.com",
    tags: ["abstract", "fluid", "color", "waves", "3d", "render"],
    collectionSlugs: [],
  },
  {
    title: "Chromium Sphere Geometry",
    slug: "chromium-sphere-geometry",
    categorySlug: "abstract",
    description: "Mirrored liquid mercury spheres floating in an atmospheric studio lighting environment.",
    width: 3840,
    height: 2160,
    orientation: "landscape",
    rawUrl: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe",
    fileType: "WEBP",
    fileSize: "5.5 MB",
    views: 31800,
    downloads: 13900,
    featured: false,
    trending: true,
    creatorName: "Milad Fakurian",
    creatorUrl: "https://unsplash.com",
    tags: ["chrome", "spheres", "silver", "abstract", "modern", "3d"],
    collectionSlugs: [],
  },

  // DARK / OLED
  {
    title: "Midnight Eclipse Abyss",
    slug: "midnight-eclipse-abyss",
    categorySlug: "dark",
    description: "Deep pure-black 0% OLED background with an ultra-fine luminous coronal halo ring.",
    width: 3840,
    height: 2160,
    orientation: "landscape",
    rawUrl: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23",
    fileType: "WEBP",
    fileSize: "3.2 MB",
    views: 65400,
    downloads: 32400,
    featured: true,
    trending: true,
    creatorName: "Darkness Lab",
    creatorUrl: "https://unsplash.com",
    tags: ["dark", "oled", "eclipse", "black", "minimal", "halo"],
    collectionSlugs: ["best-dark-wallpapers"],
  },
  {
    title: "Carbon Fiber Hex Pattern",
    slug: "carbon-fiber-hex-pattern",
    categorySlug: "dark",
    description: "High-tech woven carbon fiber weave with stealth micro-texture and subtle ambient rim lighting.",
    width: 3840,
    height: 2160,
    orientation: "landscape",
    rawUrl: "https://images.unsplash.com/photo-1550684848-fac1c5b4e853",
    fileType: "WEBP",
    fileSize: "4.7 MB",
    views: 49100,
    downloads: 23600,
    featured: true,
    trending: false,
    creatorName: "Patrick Hendry",
    creatorUrl: "https://unsplash.com",
    tags: ["carbon", "fiber", "texture", "dark", "stealth", "black"],
    collectionSlugs: ["best-dark-wallpapers"],
  },
  {
    title: "Black Smoke Nebula Tendril",
    slug: "black-smoke-nebula-tendril",
    categorySlug: "dark",
    description: "Silky black tendrils of incense smoke dancing slowly against a pitch-black abyss.",
    width: 3840,
    height: 2160,
    orientation: "landscape",
    rawUrl: "https://images.unsplash.com/photo-1509114397022-ed747cca3f65",
    fileType: "WEBP",
    fileSize: "3.9 MB",
    views: 37800,
    downloads: 16900,
    featured: false,
    trending: true,
    creatorName: "Pawel Czerwinski",
    creatorUrl: "https://unsplash.com",
    tags: ["smoke", "dark", "black", "moody", "minimal"],
    collectionSlugs: ["best-dark-wallpapers"],
  },

  // TECHNOLOGY
  {
    title: "Silicon Die Microprocessor Circuit",
    slug: "silicon-die-microprocessor-circuit",
    categorySlug: "technology",
    description: "Extreme macro detail of microscopic copper interconnects and gold traces on an integrated processor chip.",
    width: 3840,
    height: 2160,
    orientation: "landscape",
    rawUrl: "https://images.unsplash.com/photo-1518770660439-4636190af475",
    fileType: "WEBP",
    fileSize: "6.9 MB",
    views: 42100,
    downloads: 18200,
    featured: true,
    trending: false,
    creatorName: "Alexandre Debiève",
    creatorUrl: "https://unsplash.com",
    tags: ["tech", "cpu", "chip", "hardware", "circuit", "gold"],
    collectionSlugs: [],
  },
  {
    title: "Quantum Fiber Optic Matrix",
    slug: "quantum-fiber-optic-matrix",
    categorySlug: "technology",
    description: "Glowing cyan fiber optic cable ends beaming high-speed data pulses through a dark network core.",
    width: 3840,
    height: 2160,
    orientation: "landscape",
    rawUrl: "https://images.unsplash.com/photo-1544197150-b99a580bb7a8",
    fileType: "WEBP",
    fileSize: "5.8 MB",
    views: 36200,
    downloads: 15400,
    featured: false,
    trending: true,
    creatorName: "Compare Fibre",
    creatorUrl: "https://unsplash.com",
    tags: ["fiber", "optics", "blue", "network", "tech", "laser"],
    collectionSlugs: [],
  },

  // ARCHITECTURE
  {
    title: "Geometric Spiral Glass Skyscraper",
    slug: "geometric-spiral-glass-skyscraper",
    categorySlug: "architecture",
    description: "Looking straight up through a crystalline helical glass dome atrium with dazzling geometric patterns.",
    width: 3840,
    height: 2160,
    orientation: "landscape",
    rawUrl: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab",
    fileType: "WEBP",
    fileSize: "7.1 MB",
    views: 39500,
    downloads: 17100,
    featured: true,
    trending: true,
    creatorName: "Sean Pollock",
    creatorUrl: "https://unsplash.com",
    tags: ["architecture", "skyscraper", "glass", "symmetry", "modern"],
    collectionSlugs: [],
  },
  {
    title: "Brutalist Concrete Symmetrical Staircase",
    slug: "brutalist-concrete-symmetrical-staircase",
    categorySlug: "architecture",
    description: "Masterful architectural lines forming a monumental double-helix concrete staircase with dramatic lighting.",
    width: 3840,
    height: 2160,
    orientation: "landscape",
    rawUrl: "https://images.unsplash.com/photo-1513694203232-719a280e022f",
    fileType: "WEBP",
    fileSize: "6.2 MB",
    views: 28400,
    downloads: 11900,
    featured: false,
    trending: false,
    creatorName: "Scott Webb",
    creatorUrl: "https://unsplash.com",
    tags: ["stairs", "concrete", "brutalist", "lines", "shadows"],
    collectionSlugs: [],
  },

  // MOVIES & CINEMATIC
  {
    title: "Interstellar Dune Storm",
    slug: "interstellar-dune-storm",
    categorySlug: "movies",
    description: "Cinematic epic sandstorm sweeping over an alien desert planet reminiscent of deep sci-fi cinema.",
    width: 3840,
    height: 2160,
    orientation: "landscape",
    rawUrl: "https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9",
    fileType: "WEBP",
    fileSize: "6.8 MB",
    views: 46200,
    downloads: 20500,
    featured: true,
    trending: true,
    creatorName: "Cinematic Visions",
    creatorUrl: "https://unsplash.com",
    tags: ["dune", "cinema", "scifi", "movie", "storm", "desert"],
    collectionSlugs: ["cinematic-superhero-universe"],
  },
  {
    title: "Film Noir Rain Fog Street",
    slug: "film-noir-rain-fog-street",
    categorySlug: "movies",
    description: "A shadowy figure in a trench coat standing under a flickering tungsten street lamp in 1940s film grain.",
    width: 3840,
    height: 2160,
    orientation: "landscape",
    rawUrl: "https://images.unsplash.com/photo-1485846234645-a62644f84728",
    fileType: "WEBP",
    fileSize: "5.4 MB",
    views: 31900,
    downloads: 13400,
    featured: false,
    trending: false,
    creatorName: "Martin Jernberg",
    creatorUrl: "https://unsplash.com",
    tags: ["noir", "cinema", "rain", "vintage", "fog", "mystery"],
    collectionSlugs: ["cinematic-superhero-universe"],
  },

  // SUPERHEROES
  {
    title: "Dark Knight Rooftop Sentinel",
    slug: "dark-knight-rooftop-sentinel",
    categorySlug: "superheroes",
    description: "A stoic superhero silhouette perched atop a gothic gargoyle overlooking a stormy metropolitan crime-city.",
    width: 3840,
    height: 2160,
    orientation: "landscape",
    rawUrl: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5",
    fileType: "WEBP",
    fileSize: "7.3 MB",
    views: 54100,
    downloads: 26200,
    featured: true,
    trending: true,
    creatorName: "Gotham Archives",
    creatorUrl: "https://unsplash.com",
    tags: ["superhero", "batman", "darkknight", "gargoyle", "city", "rain"],
    collectionSlugs: ["cinematic-superhero-universe"],
  },
  {
    title: "Cosmic Thunderbolt Guardian",
    slug: "cosmic-thunderbolt-guardian",
    categorySlug: "superheroes",
    description: "Electrifying arcs of golden plasma lighting radiating from a powerful mythological hero stance.",
    width: 3840,
    height: 2160,
    orientation: "landscape",
    rawUrl: "https://images.unsplash.com/photo-1534447677768-be436bb09401",
    fileType: "WEBP",
    fileSize: "6.9 MB",
    views: 38500,
    downloads: 16700,
    featured: false,
    trending: true,
    creatorName: "Heroic Arts",
    creatorUrl: "https://unsplash.com",
    tags: ["hero", "lightning", "thunder", "power", "comic"],
    collectionSlugs: ["cinematic-superhero-universe"],
  },

  // ANIMALS
  {
    title: "Arctic Snow Leopard Gaze",
    slug: "arctic-snow-leopard-gaze",
    categorySlug: "animals",
    description: "Close-up piercing eyes of a snow leopard amidst falling snowflakes with breathtaking 4K fur detail.",
    width: 3840,
    height: 2160,
    orientation: "landscape",
    rawUrl: "https://images.unsplash.com/photo-1561731216-c3a4d99437d5",
    fileType: "WEBP",
    fileSize: "7.7 MB",
    views: 48300,
    downloads: 21500,
    featured: true,
    trending: true,
    creatorName: "Zdeněk Macháček",
    creatorUrl: "https://unsplash.com",
    tags: ["leopard", "wildlife", "snow", "eyes", "cat", "predator"],
    collectionSlugs: [],
  },
  {
    title: "Majestic Stifled Lion Pride",
    slug: "majestic-stifled-lion-pride",
    categorySlug: "animals",
    description: "Regal lion with dark flowing mane resting on African savanna rock during dramatic twilight.",
    width: 3840,
    height: 2160,
    orientation: "landscape",
    rawUrl: "https://images.unsplash.com/photo-1534188753412-3e26d0d618d6",
    fileType: "WEBP",
    fileSize: "7.1 MB",
    views: 42600,
    downloads: 19100,
    featured: false,
    trending: true,
    creatorName: "Markus Spiske",
    creatorUrl: "https://unsplash.com",
    tags: ["lion", "safari", "wildlife", "king", "animals"],
    collectionSlugs: [],
  },

  // AESTHETIC
  {
    title: "Pastel Sunset Cloud Waves",
    slug: "pastel-sunset-cloud-waves",
    categorySlug: "aesthetic",
    description: "Soft cotton-candy clouds bathed in gradient blush pink, lavender, and gentle apricot evening tones.",
    width: 3840,
    height: 2160,
    orientation: "landscape",
    rawUrl: "https://images.unsplash.com/photo-1517483000871-1dbf64a6e1c6",
    fileType: "WEBP",
    fileSize: "5.3 MB",
    views: 49200,
    downloads: 22700,
    featured: true,
    trending: true,
    creatorName: "Laura Vinck",
    creatorUrl: "https://unsplash.com",
    tags: ["aesthetic", "pastel", "clouds", "pink", "sky", "lofi"],
    collectionSlugs: [],
  },
  {
    title: "Lofi Neon Japanese Bodega",
    slug: "lofi-neon-japanese-bodega",
    categorySlug: "aesthetic",
    description: "Warm glowing convenience store front with ambient vending machines on a tranquil evening street.",
    width: 3840,
    height: 2160,
    orientation: "landscape",
    rawUrl: "https://images.unsplash.com/photo-1542051841857-5f90071e7989",
    fileType: "WEBP",
    fileSize: "6.1 MB",
    views: 37900,
    downloads: 17300,
    featured: false,
    trending: false,
    creatorName: "Clay Banks",
    creatorUrl: "https://unsplash.com",
    tags: ["lofi", "aesthetic", "vending", "japan", "chill", "night"],
    collectionSlugs: [],
  },

  // CITY
  {
    title: "Manhattan Twilight Skyline Blue Hour",
    slug: "manhattan-twilight-skyline-blue-hour",
    categorySlug: "city",
    description: "Iconic illuminated Empire State Building and Midtown Manhattan skyscrapers glistening in twilight blue hour.",
    width: 3840,
    height: 2160,
    orientation: "landscape",
    rawUrl: "https://images.unsplash.com/photo-1514565131-fce0801e5785",
    fileType: "WEBP",
    fileSize: "7.9 MB",
    views: 59400,
    downloads: 28400,
    featured: true,
    trending: true,
    creatorName: "Pedro Lastra",
    creatorUrl: "https://unsplash.com",
    tags: ["newyork", "city", "skyline", "manhattan", "lights", "night"],
    collectionSlugs: [],
  },
  {
    title: "Tokyo Shinjuku Crossings",
    slug: "tokyo-shinjuku-crossings",
    categorySlug: "city",
    description: "Dazzling neon signs, luminous transit ribbons, and iconic urban energy in Tokyo's vibrant heart.",
    width: 3840,
    height: 2160,
    orientation: "landscape",
    rawUrl: "https://images.unsplash.com/photo-1503899036084-c55cdd92da26",
    fileType: "WEBP",
    fileSize: "7.3 MB",
    views: 45700,
    downloads: 20100,
    featured: false,
    trending: true,
    creatorName: "Jezael Melgoza",
    creatorUrl: "https://unsplash.com",
    tags: ["tokyo", "japan", "city", "crosswalk", "lights"],
    collectionSlugs: [],
  },

  // FANTASY
  {
    title: "Floating Citadel in the Clouds",
    slug: "floating-citadel-in-the-clouds",
    categorySlug: "fantasy",
    description: "Magical airborne ancient towers suspended among towering cumulonimbus clouds with cascading waterfalls.",
    width: 3840,
    height: 2160,
    orientation: "landscape",
    rawUrl: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23",
    fileType: "WEBP",
    fileSize: "7.5 MB",
    views: 48600,
    downloads: 22800,
    featured: true,
    trending: true,
    creatorName: "Mythic Dreamer",
    creatorUrl: "https://unsplash.com",
    tags: ["fantasy", "citadel", "magic", "castle", "clouds", "epic"],
    collectionSlugs: [],
  },
  {
    title: "Ancient Enchanted Grove Runes",
    slug: "ancient-enchanted-grove-runes",
    categorySlug: "fantasy",
    description: "Gleaming blue mystical runes engraved upon ancient mossy stones deep inside a fairytale woodland.",
    width: 3840,
    height: 2160,
    orientation: "landscape",
    rawUrl: "https://images.unsplash.com/photo-1448375240586-882707db888b",
    fileType: "WEBP",
    fileSize: "6.8 MB",
    views: 33100,
    downloads: 14700,
    featured: false,
    trending: false,
    creatorName: "Forest Witch",
    creatorUrl: "https://unsplash.com",
    tags: ["fantasy", "runes", "magic", "forest", "enchanted"],
    collectionSlugs: [],
  },

  // SPORTS
  {
    title: "Alpine Freeride Powder Blizzard",
    slug: "alpine-freeride-powder-blizzard",
    categorySlug: "sports",
    description: "Extreme powder skier carving a massive snow plume down a pristine untouched Alaskan spine wall in 4K.",
    width: 3840,
    height: 2160,
    orientation: "landscape",
    rawUrl: "https://images.unsplash.com/photo-1461896836934-ffe607ba8211",
    fileType: "WEBP",
    fileSize: "6.5 MB",
    views: 31200,
    downloads: 13900,
    featured: false,
    trending: true,
    creatorName: "Action Powder",
    creatorUrl: "https://unsplash.com",
    tags: ["skiing", "snow", "sports", "extreme", "winter", "action"],
    collectionSlugs: [],
  },
  {
    title: "Surfer Inside Emerald Tube Wave",
    slug: "surfer-inside-emerald-tube-wave",
    categorySlug: "sports",
    description: "Spectacular inside view of a barreling crystal turquoise Polynesian ocean wave.",
    width: 3840,
    height: 2160,
    orientation: "landscape",
    rawUrl: "https://images.unsplash.com/photo-1502680390469-be75c86b636f",
    fileType: "WEBP",
    fileSize: "7.0 MB",
    views: 29800,
    downloads: 12500,
    featured: false,
    trending: false,
    creatorName: "Jeremy Bishop",
    creatorUrl: "https://unsplash.com",
    tags: ["surf", "wave", "ocean", "sports", "water"],
    collectionSlugs: [],
  },

  // DUAL MONITOR & ULTRAWIDE (21:9 and 32:9)
  {
    title: "Panoramic Yosemite Valley Vista Ultrawide",
    slug: "panoramic-yosemite-valley-vista-ultrawide",
    categorySlug: "nature",
    description: "Expansive 3440x1440p 21:9 ultrawide panoramic capture of Yosemite Valley, El Capitan, and Half Dome at golden hour.",
    width: 3440,
    height: 1440,
    orientation: "ultrawide",
    rawUrl: "https://images.unsplash.com/photo-1426604966848-d7adac402bff",
    fileType: "WEBP",
    fileSize: "8.4 MB",
    views: 41800,
    downloads: 19600,
    featured: true,
    trending: true,
    creatorName: "Ansel Horizon",
    creatorUrl: "https://unsplash.com",
    tags: ["ultrawide", "21:9", "yosemite", "nature", "valley", "panoramic"],
    collectionSlugs: ["dual-monitors-and-ultrawide", "aesthetic-nature-wilderness"],
  },
  {
    title: "Cyberpunk Megalopolis Dual Monitor 32:9",
    slug: "cyberpunk-megalopolis-dual-monitor-32-9",
    categorySlug: "cyberpunk",
    description: "Super ultrawide 5120x1440 wallpaper spanning across dual displays, showing endless neon skyline and flying transports.",
    width: 5120,
    height: 1440,
    orientation: "ultrawide",
    rawUrl: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5",
    fileType: "WEBP",
    fileSize: "9.2 MB",
    views: 53200,
    downloads: 25400,
    featured: true,
    trending: true,
    creatorName: "Synth Megacity",
    creatorUrl: "https://unsplash.com",
    tags: ["ultrawide", "32:9", "dualmonitor", "cyberpunk", "panoramic"],
    collectionSlugs: ["dual-monitors-and-ultrawide", "cyberpunk-neon-cityscapes"],
  },
  {
    title: "Cosmic Nebula Panorama Ultrawide",
    slug: "cosmic-nebula-panorama-ultrawide",
    categorySlug: "space",
    description: "Ultra wide 3440x1440 wallpaper featuring a sweeping galactic collision and starfield designed for curved monitors.",
    width: 3440,
    height: 1440,
    orientation: "ultrawide",
    rawUrl: "https://images.unsplash.com/photo-1451187580459-43490279c0fa",
    fileType: "WEBP",
    fileSize: "8.1 MB",
    views: 39700,
    downloads: 18100,
    featured: true,
    trending: true,
    creatorName: "Cosmo Horizon",
    creatorUrl: "https://unsplash.com",
    tags: ["ultrawide", "21:9", "space", "galaxy", "stars", "curved"],
    collectionSlugs: ["dual-monitors-and-ultrawide", "deep-space-cosmic-horizons"],
  },
  {
    title: "Supercar Mountain Pass Ultrawide",
    slug: "supercar-mountain-pass-ultrawide",
    categorySlug: "cars",
    description: "Cinematic 3440x1440 frame of a luxury exotic sports car speeding along a dramatic Swiss pass cliffside.",
    width: 3440,
    height: 1440,
    orientation: "ultrawide",
    rawUrl: "https://images.unsplash.com/photo-1617814076367-b759c7d7e738",
    fileType: "WEBP",
    fileSize: "7.8 MB",
    views: 34200,
    downloads: 15300,
    featured: false,
    trending: true,
    creatorName: "Speed Alpine",
    creatorUrl: "https://unsplash.com",
    tags: ["ultrawide", "21:9", "cars", "supercar", "alps", "speed"],
    collectionSlugs: ["dual-monitors-and-ultrawide", "best-car-wallpapers"],
  },

  // 1440p / 1080p High-Quality Variants
  {
    title: "Minimalist Nordic Pine Mist 1440p",
    slug: "minimalist-nordic-pine-mist-1440p",
    categorySlug: "minimal",
    description: "Calming 2560x1440 QHD wallpaper of quiet Scandinavian pine forest in morning mist.",
    width: 2560,
    height: 1440,
    orientation: "landscape",
    rawUrl: "https://images.unsplash.com/photo-1448375240586-882707db888b",
    fileType: "WEBP",
    fileSize: "4.9 MB",
    views: 31500,
    downloads: 14100,
    featured: false,
    trending: false,
    creatorName: "Nordic Frames",
    creatorUrl: "https://unsplash.com",
    tags: ["1440p", "minimal", "forest", "nature", "mist"],
    collectionSlugs: ["best-minimal-wallpapers"],
  },
  {
    title: "Synthwave Sunset Grid Road 1440p",
    slug: "synthwave-sunset-grid-road-1440p",
    categorySlug: "gaming",
    description: "Retro 80s outrun road towards a giant digital wireframe sun with chrome palm trees.",
    width: 2560,
    height: 1440,
    orientation: "landscape",
    rawUrl: "https://images.unsplash.com/photo-1579546929518-9e396f3cc809",
    fileType: "WEBP",
    fileSize: "5.2 MB",
    views: 29400,
    downloads: 13200,
    featured: false,
    trending: false,
    creatorName: "Outrun Studio",
    creatorUrl: "https://unsplash.com",
    tags: ["1440p", "synthwave", "outrun", "gaming", "neon", "sunset"],
    collectionSlugs: ["best-4k-gaming-wallpapers"],
  },
  {
    title: "Tokyo Rain Crossing 1080p",
    slug: "tokyo-rain-crossing-1080p",
    categorySlug: "city",
    description: "Optimized 1920x1080 Full HD wallpaper of umbrellas reflecting neon signs in bustling Shibuya.",
    width: 1920,
    height: 1080,
    orientation: "landscape",
    rawUrl: "https://images.unsplash.com/photo-1503899036084-c55cdd92da26",
    fileType: "WEBP",
    fileSize: "3.4 MB",
    views: 24100,
    downloads: 10800,
    featured: false,
    trending: false,
    creatorName: "Shibuya Lens",
    creatorUrl: "https://unsplash.com",
    tags: ["1080p", "tokyo", "city", "rain", "lights"],
    collectionSlugs: [],
  },
  {
    title: "Solitary Desert Stargazer 1080p",
    slug: "solitary-desert-stargazer-1080p",
    categorySlug: "space",
    description: "A lonely figure gazing upward at shooting stars in the dark desert night in 1920x1080.",
    width: 1920,
    height: 1080,
    orientation: "landscape",
    rawUrl: "https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86",
    fileType: "WEBP",
    fileSize: "3.2 MB",
    views: 21500,
    downloads: 9800,
    featured: false,
    trending: false,
    creatorName: "Astro Wanderer",
    creatorUrl: "https://unsplash.com",
    tags: ["1080p", "space", "stars", "desert", "lonely"],
    collectionSlugs: ["deep-space-cosmic-horizons"],
  },
  {
    title: "Matte Black Lambo Headlights 1440p",
    slug: "matte-black-lambo-headlights-1440p",
    categorySlug: "cars",
    description: "Menacing Y-shaped LED headlights slicing through midnight shadows in 2560x1440.",
    width: 2560,
    height: 1440,
    orientation: "landscape",
    rawUrl: "https://images.unsplash.com/photo-1617814076367-b759c7d7e738",
    fileType: "WEBP",
    fileSize: "4.8 MB",
    views: 35900,
    downloads: 16200,
    featured: false,
    trending: true,
    creatorName: "Bespoke Auto",
    creatorUrl: "https://unsplash.com",
    tags: ["1440p", "cars", "lamborghini", "dark", "headlights"],
    collectionSlugs: ["best-car-wallpapers"],
  },
  {
    title: "Anime Floating Sky Islands 1440p",
    slug: "anime-floating-sky-islands-1440p",
    categorySlug: "anime",
    description: "Lush floating green isles with ancient ruins hovering peacefully in a boundless azure sky.",
    width: 2560,
    height: 1440,
    orientation: "landscape",
    rawUrl: "https://images.unsplash.com/photo-1534447677768-be436bb09401",
    fileType: "WEBP",
    fileSize: "5.1 MB",
    views: 38200,
    downloads: 17400,
    featured: false,
    trending: true,
    creatorName: "Ghibli Horizon",
    creatorUrl: "https://unsplash.com",
    tags: ["1440p", "anime", "sky", "floating", "fantasy"],
    collectionSlugs: ["best-anime-wallpapers"],
  },
  {
    title: "Dark Minimalist Wave Gradient 1080p",
    slug: "dark-minimalist-wave-gradient-1080p",
    categorySlug: "minimal",
    description: "Smooth subtle black to charcoal gray waves with zero banding for minimalists in 1080p.",
    width: 1920,
    height: 1080,
    orientation: "landscape",
    rawUrl: "https://images.unsplash.com/photo-1507499739999-097706ad8914",
    fileType: "WEBP",
    fileSize: "2.8 MB",
    views: 29800,
    downloads: 14200,
    featured: false,
    trending: false,
    creatorName: "Minimal Lab",
    creatorUrl: "https://unsplash.com",
    tags: ["1080p", "minimal", "dark", "gradient", "black"],
    collectionSlugs: ["best-minimal-wallpapers", "best-dark-wallpapers"],
  },
  {
    title: "Neon Cyber Samurai Katana",
    slug: "neon-cyber-samurai-katana",
    categorySlug: "cyberpunk",
    description: "Cybernetic warrior with an energized plasma blade reflected in rain pools during a dark midnight duel.",
    width: 3840,
    height: 2160,
    orientation: "landscape",
    rawUrl: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5",
    fileType: "WEBP",
    fileSize: "7.1 MB",
    views: 48500,
    downloads: 23100,
    featured: true,
    trending: true,
    creatorName: "Kenji Cyber",
    creatorUrl: "https://unsplash.com",
    tags: ["samurai", "cyberpunk", "katana", "neon", "warrior", "rain"],
    collectionSlugs: ["cyberpunk-neon-cityscapes", "best-4k-gaming-wallpapers"],
  },
  {
    title: "Deep Space Quantum Wormhole",
    slug: "deep-space-quantum-wormhole",
    categorySlug: "space",
    description: "A theoretical gravitational lens distorting spacetime into a glowing accretion ring in deep space.",
    width: 3840,
    height: 2160,
    orientation: "landscape",
    rawUrl: "https://images.unsplash.com/photo-1451187580459-43490279c0fa",
    fileType: "WEBP",
    fileSize: "8.3 MB",
    views: 52400,
    downloads: 25100,
    featured: true,
    trending: true,
    creatorName: "Astro Physics Hub",
    creatorUrl: "https://unsplash.com",
    tags: ["wormhole", "blackhole", "space", "quantum", "gravity"],
    collectionSlugs: ["deep-space-cosmic-horizons"],
  },
  {
    title: "Aurora Borealis Fjords Ultrawide",
    slug: "aurora-borealis-fjords-ultrawide",
    categorySlug: "nature",
    description: "Electric emerald northern lights dancing across a midnight fjord in stunning 3440x1440 21:9 ultrawide.",
    width: 3440,
    height: 1440,
    orientation: "ultrawide",
    rawUrl: "https://images.unsplash.com/photo-1506744038136-46273834b3fb",
    fileType: "WEBP",
    fileSize: "8.7 MB",
    views: 46800,
    downloads: 21900,
    featured: true,
    trending: true,
    creatorName: "Nordic Lights",
    creatorUrl: "https://unsplash.com",
    tags: ["aurora", "ultrawide", "21:9", "fjord", "green", "night"],
    collectionSlugs: ["dual-monitors-and-ultrawide", "aesthetic-nature-wilderness"],
  },
  {
    title: "Cyberpunk Rain Samurai Hologram 4K",
    slug: "cyberpunk-rain-samurai-hologram-4k",
    categorySlug: "cyberpunk",
    description: "Towering neon holographic billboards reflecting upon wet pavement with an enigmatic armored nomad in 4K.",
    width: 3840,
    height: 2160,
    orientation: "landscape",
    rawUrl: "https://images.unsplash.com/photo-1514565131-fce0801e5785",
    fileType: "WEBP",
    fileSize: "7.8 MB",
    views: 39100,
    downloads: 18400,
    featured: true,
    trending: true,
    creatorName: "Tokyo Cyber",
    creatorUrl: "https://unsplash.com",
    tags: ["cyberpunk", "hologram", "rain", "neon", "tokyo"],
    collectionSlugs: ["cyberpunk-neon-cityscapes"],
  },
  {
    title: "Deep Space Galactic Core 8K",
    slug: "deep-space-galactic-core-8k",
    categorySlug: "space",
    description: "Ultra-high resolution 7680x4320 8K capture of billions of stars glowing within the central galactic bulge.",
    width: 7680,
    height: 4320,
    orientation: "landscape",
    rawUrl: "https://images.unsplash.com/photo-1451187580459-43490279c0fa",
    fileType: "WEBP",
    fileSize: "14.2 MB",
    views: 67200,
    downloads: 34100,
    featured: true,
    trending: true,
    creatorName: "James Webb Observatory",
    creatorUrl: "https://unsplash.com",
    tags: ["8k", "space", "galaxy", "stars", "cosmos", "ultra"],
    collectionSlugs: ["deep-space-cosmic-horizons"],
  },
  {
    title: "Stealth Fighter Jet In Clouds 4K",
    slug: "stealth-fighter-jet-in-clouds-4k",
    categorySlug: "technology",
    description: "Radar-evading stealth fighter jet cutting silently through supersonic cloud vapors at sunrise.",
    width: 3840,
    height: 2160,
    orientation: "landscape",
    rawUrl: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23",
    fileType: "WEBP",
    fileSize: "6.9 MB",
    views: 43100,
    downloads: 19800,
    featured: false,
    trending: true,
    creatorName: "Aero Dynamics",
    creatorUrl: "https://unsplash.com",
    tags: ["jet", "stealth", "aviation", "military", "clouds", "speed"],
    collectionSlugs: [],
  },
  {
    title: "Minimalist Black Hole Gravitational Singularity",
    slug: "minimalist-black-hole-gravitational-singularity",
    categorySlug: "dark",
    description: "Minimalist representation of an event horizon curving light into a razor-thin photon sphere on pure black.",
    width: 3840,
    height: 2160,
    orientation: "landscape",
    rawUrl: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23",
    fileType: "WEBP",
    fileSize: "3.5 MB",
    views: 58200,
    downloads: 29400,
    featured: true,
    trending: true,
    creatorName: "Astrophysics Art",
    creatorUrl: "https://unsplash.com",
    tags: ["blackhole", "dark", "oled", "minimal", "space", "clean"],
    collectionSlugs: ["best-dark-wallpapers", "best-minimal-wallpapers"],
  },
  {
    title: "Golden Hour Supercar Coast Drive",
    slug: "golden-hour-supercar-coast-drive",
    categorySlug: "cars",
    description: "Aerodynamic lines of a bespoke hypercar catching the dying rays of the sun along Big Sur cliffs.",
    width: 3840,
    height: 2160,
    orientation: "landscape",
    rawUrl: "https://images.unsplash.com/photo-1503376780353-7e6692767b70",
    fileType: "WEBP",
    fileSize: "7.3 MB",
    views: 42100,
    downloads: 18900,
    featured: false,
    trending: true,
    creatorName: "Pacific Motor",
    creatorUrl: "https://unsplash.com",
    tags: ["hypercar", "coast", "sunset", "goldenhour", "cars"],
    collectionSlugs: ["best-car-wallpapers"],
  },
  {
    title: "Neon Gaming Keyboard Macro Violet",
    slug: "neon-gaming-keyboard-macro-violet",
    categorySlug: "gaming",
    description: "Custom mechanical switch keyboard with deep violet and neon cyan pudding keycaps in razor sharp 4K.",
    width: 3840,
    height: 2160,
    orientation: "landscape",
    rawUrl: "https://images.unsplash.com/photo-1550745165-9bc0b252726f",
    fileType: "WEBP",
    fileSize: "6.1 MB",
    views: 35100,
    downloads: 16200,
    featured: false,
    trending: false,
    creatorName: "Keeb Life",
    creatorUrl: "https://unsplash.com",
    tags: ["keyboard", "gaming", "rgb", "pc", "macro"],
    collectionSlugs: ["best-4k-gaming-wallpapers"],
  },
];

async function main() {
  console.log("🌱 Seeding WallPC database with categories, collections, and wallpapers...");

  // 1. Clean existing records
  await prisma.downloadEvent.deleteMany();
  await prisma.viewEvent.deleteMany();
  await prisma.collectionWallpaper.deleteMany();
  await prisma.wallpaperTag.deleteMany();
  await prisma.tag.deleteMany();
  await prisma.collection.deleteMany();
  await prisma.wallpaper.deleteMany();
  await prisma.category.deleteMany();

  // 2. Create Categories
  const categoryMap = new Map<string, string>();
  for (const cat of CATEGORIES) {
    const created = await prisma.category.create({
      data: cat,
    });
    categoryMap.set(cat.slug, created.id);
  }
  console.log(`✅ Created ${CATEGORIES.length} categories.`);

  // 3. Create Collections
  const collectionMap = new Map<string, string>();
  for (const col of COLLECTIONS) {
    const created = await prisma.collection.create({
      data: col,
    });
    collectionMap.set(col.slug, created.id);
  }
  console.log(`✅ Created ${COLLECTIONS.length} collections.`);

  // 4. Create Wallpapers & Tags
  const tagMap = new Map<string, string>();

  for (let i = 0; i < RAW_WALLPAPERS.length; i++) {
    const raw = RAW_WALLPAPERS[i];
    const categoryId = categoryMap.get(raw.categorySlug);

    if (!categoryId) {
      console.warn(`Category not found for slug: ${raw.categorySlug}`);
      continue;
    }

    // Unsplash URLs with variants
    const rawBase = raw.rawUrl;
    const fileUrl4k = `${rawBase}?auto=format&fit=crop&w=3840&h=2160&q=90`;
    const fileUrl1440p = `${rawBase}?auto=format&fit=crop&w=2560&h=1440&q=85`;
    const fileUrl1080p = `${rawBase}?auto=format&fit=crop&w=1920&h=1080&q=80`;
    const previewUrl = `${rawBase}?auto=format&fit=crop&w=1600&h=900&q=80`;
    const thumbnailUrl = `${rawBase}?auto=format&fit=crop&w=720&h=405&q=75`;

    // Calculate dynamic trending score
    // trending_score = recent_downloads * 3 + recent_views * 1 + recency_bonus
    const recencyBonus = 500 - i * 8;
    const trendingScore = raw.downloads * 3 + raw.views * 0.5 + Math.max(0, recencyBonus);

    const wallpaper = await prisma.wallpaper.create({
      data: {
        title: raw.title,
        slug: raw.slug,
        description: raw.description,
        categoryId,
        resolutionWidth: raw.width,
        resolutionHeight: raw.height,
        orientation: raw.orientation,
        fileUrl: fileUrl4k,
        fileUrl4k,
        fileUrl1440p,
        fileUrl1080p,
        thumbnailUrl,
        previewUrl,
        fileType: raw.fileType,
        fileSize: raw.fileSize,
        views: raw.views,
        downloads: raw.downloads,
        trendingScore,
        featured: raw.featured,
        trending: raw.trending,
        published: true,
        creatorName: raw.creatorName,
        creatorUrl: raw.creatorUrl,
        license: "Free for personal desktop use (Unsplash License)",
      },
    });

    // Handle Tags
    for (const tagName of raw.tags) {
      const tagSlug = tagName.toLowerCase().replace(/[^a-z0-9]+/g, "-");
      let tagId = tagMap.get(tagSlug);
      if (!tagId) {
        const tagRecord = await prisma.tag.upsert({
          where: { slug: tagSlug },
          update: {},
          create: { name: tagName, slug: tagSlug },
        });
        tagId = tagRecord.id;
        tagMap.set(tagSlug, tagId);
      }

      await prisma.wallpaperTag.create({
        data: {
          wallpaperId: wallpaper.id,
          tagId,
        },
      });
    }

    // Link to Collections
    if (raw.collectionSlugs) {
      for (const colSlug of raw.collectionSlugs) {
        const colId = collectionMap.get(colSlug);
        if (colId) {
          await prisma.collectionWallpaper.create({
            data: {
              collectionId: colId,
              wallpaperId: wallpaper.id,
              order: i,
            },
          });
        }
      }
    }

    // Create a few realistic download events
    for (let d = 0; d < 3; d++) {
      await prisma.downloadEvent.create({
        data: {
          wallpaperId: wallpaper.id,
          resolution: raw.width >= 3840 ? "4k" : "1440p",
          anonymousIdentifier: `anon_${Math.random().toString(36).substring(2, 10)}`,
        },
      });
    }
  }

  console.log(`✅ Seeded ${RAW_WALLPAPERS.length} wallpapers with tags and collection links.`);
  console.log("🚀 WallPC database seed complete!");
}

main()
  .catch((e) => {
    console.error("Error seeding database:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
